In [137]:
import numpy as np

## Exercicio 1
1. A SEC3 (Securities and Exchange Comission) está
investigando uma empresa de serviços financeiros
que tem 86 corretores. A SEC decide revisar os re-
gistros de uma amostra aleatória de 10 corretores.
Descreva como essa investigação poderia ser feita.
Então, use a tecnologia para gerar uma lista de 10
números aleatórios de 1 a 86 e ordene a lista.

In [138]:
agents: [int] = np.random.randint(0, 87, 10)
agents.sort()
agents

array([ 5, 15, 19, 24, 46, 53, 54, 59, 64, 71])

# Exercicio 2
Um departamento de controle de qualidade está
testando 25 smartphones de um carregamento de
300. Descreva como esse teste poderia ser feito.
Então, use a tecnologia para gerar uma lista de 25
números aleatórios de 1 a 300 e ordene a lista.

In [139]:
smartphones: [int] = np.random.randint(1, 301, 25)
smartphones.sort()
smartphones

array([  2,   2,   4,   6,  25,  53,  58,  61,  81,  92,  98, 133, 147,
       149, 151, 159, 162, 163, 167, 178, 181, 187, 189, 253, 282])

# Exercicio 3
Considere a população de dez dígitos: 0, 1, 2, 3, 4,
5, 6, 7, 8 e 9. Selecione três amostras aleatórias de
cinco dígitos dessa lista. Encontre a média de cada
amostra. Compare seus resultados com a média da
população. Comente seus resultados. (Dica: para
encontrar a média, some os dados e divida o resul-
tado pelo número de elementos.)

In [140]:
numbers: [int] = np.arange(10)
chosen: [[int]] = [np.random.choice(numbers, 3, replace=False) for x in range(3)]
[print(f"{x}: {x.mean()}") for x in chosen]

[9 8 2]: 6.333333333333333
[9 6 1]: 5.333333333333333
[1 5 2]: 2.6666666666666665


[None, None, None]

# Exercicio 4
Considere a população de 41 números inteiros de
0 a 40. Qual é a média desses números? Selecio-
ne três amostras aleatórias de sete números dessa
lista. Encontre a média de cada amostra. Com-
pare seus resultados com a média da população.
Comente seus resultados.

In [141]:
numbers: [int] = np.arange(41)
chosen: [[int]] = [np.random.choice(numbers, 7, replace=False) for x in range(3)]
print(f"{numbers.mean()}")
[print(f"{x}: {x.mean()}") for x in chosen]

20.0
[ 6 33  2  5 23 13 39]: 17.285714285714285
[22 39 15 13  4 40 25]: 22.571428571428573
[36 19 34 22 25  2 13]: 21.571428571428573


[None, None, None]

# Exercicio 5
Use números aleatórios para simular a jogada
de um dado de seis faces 60 vezes. Quantas vezes
você obteve cada número de 1 a 6? Os resultados
são os que você esperava?

In [142]:
dice: dict[int,int] = {x:0 for x in range(1,7)}

for i in range(60):
  dice[np.random.randint(1, 7)] += 1

dice

{1: 9, 2: 12, 3: 10, 4: 5, 5: 12, 6: 12}

# Exercicio 7
Use números aleatórios para simular o lançamen-
to de uma moeda 100 vezes, em que 0 representa
cara e 1 coroa. Quantas vezes você obteve cada
número? Os resultados são os que você esperava?

In [143]:
heads_tails: dict[int,int] = {0:0, 1:0}

for i in range(100):
  heads_tails[np.random.randint(0,2)] += 1

heads_tails

{0: 44, 1: 56}